Fix grammatical errors in documentation CONTRIBUTING.md
AimRT/AimRT pull request #71
Opened 2024-10-31 13:56 UTC by rahuldave2005

Description
This pull request fixes grammatical errors in the documentation to improve readability and clarity.

Changes made:
Corrected grammatical errors
Revised wording
These changes do not affect any functional parts of the project, and they only enhance the documentation.
Please review and let me know if any further improvements are needed. Thank you!

fixes Issue #70

2024-11-01 02:00 UTC, zhangyi1357 requested changes
Thanks for your work!

Example commit messages should not be modified, as reasons are explained in the relevant section.

2024-11-01 02:05 UTC, zhangyi1357 commented on CONTRIBUTING.md
> +  you can either add more commits or rebase and force-push (both styles are accepted).
A comma here might be clearer, I think.

2024-11-06 01:55 UTC, zhangyi1357 commented
@rahuldave2005  Your PR only needs a few minor changes to be merged.  You can make the changes when you have time.

2025-02-05 09:25 UTC, AimRT commented
Close as inactive

2025-02-05 09:25 UTC, closed without merging